// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9WMDS_Mis8bUAX--DW1RU9xQUQyc-9wg',
    appId: '1:1066716126096:web:790cdf0f5cc50cee7bf115',
    messagingSenderId: '1066716126096',
    projectId: 'iput-sns',
    authDomain: 'iput-sns.firebaseapp.com',
    storageBucket: 'iput-sns.appspot.com',
    measurementId: 'G-0MCVQ9HXKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbWRKYWCGAeSNtKM-VRGRzJVFco57bVxw',
    appId: '1:1066716126096:android:2c7b54d8387a2abe7bf115',
    messagingSenderId: '1066716126096',
    projectId: 'iput-sns',
    storageBucket: 'iput-sns.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Tht42RtzRLauFRJNdNulMxdDbj3hmX4',
    appId: '1:1066716126096:ios:372de15b35360ade7bf115',
    messagingSenderId: '1066716126096',
    projectId: 'iput-sns',
    storageBucket: 'iput-sns.appspot.com',
    iosClientId: '1066716126096-hkcrupq9n313pj42jucnsvit0vm13eq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Tht42RtzRLauFRJNdNulMxdDbj3hmX4',
    appId: '1:1066716126096:ios:1e958a4028474fa47bf115',
    messagingSenderId: '1066716126096',
    projectId: 'iput-sns',
    storageBucket: 'iput-sns.appspot.com',
    iosClientId: '1066716126096-hk3ndioj1tn97pojababuvf9vk5bf891.apps.googleusercontent.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
