name: app
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0-366.0.dev <4.0.0"

dependencies:
  go_router:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.12.0
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  firebase_storage:
  file_picker:
  google_sign_in: ^6.0.2
  cloud_firestore: ^4.4.5
  dropdown_button2: ^2.0.0
  carousel_slider: ^4.2.1
  expandable_page_view: ^1.0.17
  stylish_bottom_bar: ^1.0.0
  flutter_riverpod:
  like_button: ^2.0.5
  badges: ^3.1.1
  bouncing_widget: ^2.0.0
  pull_down_button: ^0.8.2
  chat_bubbles: ^1.4.0
  glassmorphism: ^3.0.0
  image_picker: ^0.8.7+4
  dropdown_search: ^5.0.6
  animated_floating_buttons: ^0.0.2
  flutter_hooks:
  riverpod_annotation:
  custom_navigation_bar:

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/iconnect.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner:
  riverpod_generator:
  analyzer: ^5.12.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
